services:
  nginx:
    container_name: webserver
    build:
      context: ./_build
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: dev.ibch.ru
      # HTTP_PORT: 80
      # HTTPS_PORT: 443
      # SSL_MODE: self     # варианты: no, self, certbot
      # CERT_DAYS: 365
      # LISTEN_ADDR: 0.0.0.0
      # EMAIL: certbot@gmail.com # почта для обновления сертификатов, если установлен режим certbot
    volumes:
      - ./config-templates:/etc/config-templates
      - ./html:/usr/share/nginx/html
      - letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt: